output = "pdf"
multi_page = true

[features]
table_of_contents = false
preserve_hard_line_breaks = false
math_rendering = false
advanced_typography = false

[margins]
top = 60
bottom = 60
left = 50
right = 50

[debug]
bounding_boxes = true
